.TH system-config-repo 1
.SH NAME
system-config-repo \- Yum repository GUI interface

.SH SYNOPSIS
.B system-config-repo [repo]
.PP
[repo] is the name of a yum repository file, by default interpreted
relative to /etc/yum.repos.d.

.SH EXAMPLE
.IP "" 4
$ system-config-repo fedora.repo
.PP
Displays info on the Fedora release repositories.

.SH DESCRIPTION
system-config-repo provides a graphical interface to a single configuration
file in /etc/yum.repos.d. Using the GUI a user can enable/disable the
repository, view the package list and inspect the signing key used
inclusive fingerprint.

.SH DATA SOURCES
To gather more info, application checks if there is a package with
information (summary, description, icon, etc.) on the repository file.
The first check is if the repository is owned by a package. If this
fails, application tries to locate a package which requires the repository
file. In any case, in order to be used a package must provide
"repo-gui" to be used. If no package is found it defaults to "Default".
.PP
The  package found this way is used as <package> in the following.
.PP
The gui gathers data from different sources to provide info on the package.
In priority it uses:
.IP \(bu 3
Data in the directory /usr/share/system-config-repo/repos/<package>.
Description, summary etc are represented as files named description.txt,
summary .txt etc. A file named icon.png is displayed if present.
.IP \(bu 3
The appdata file /usr/share/appdata/<package>.appdata.xml. This file
contains possibly localized description and summary.
.IP \(bu 3
The rpm database provides a non-localized version of summary and
description.
.IP \(bu 3
The path  /usr/share/system-config-repo/Default contains last resort
default values.

.SH RESTRICTED OPERATION
A repository file which is writable by current user is updated directly.
If the repo file is not writeable, an attempt to update it using sudo(8)
is done. The package installs a sudo config file which allow all members
of the wheel group to update the repository file.

.SH LICENSE
This is open source software under the MIT license, see the LICENSE file.

.SH FILES
.TP
/usr/share/system-config-repo/repos
Specific resources (icon, summary) for different repo-id.
.TP
/etc/sudooers.d/system-config-repo
Allows members of the wheel group to update repository files.

.SH SEE ALSO
.TP
https://github.com/leamas/system-config-repo
    Source, issue tracker, etc.
.TP
yum.conf(5)
    Format for /etc/yum.repos.d files.
.TP
yum-config-manager(1)
    CLI tool with similar scope.

yum-config-manager(1)
    CLI tool with similar scope.

