#!/bin/bash
#
# lpf: create a fresh rpm to try.
#

cd $(dirname $(readlink -fn $0))/..

[ -n "$(git diff system-config-repo.spec)" ] && {
    "You have changes in system-config-repo.spec, please stash" >&2
    exit 2
}

set -x

mkdir dist 2>/dev/null || :
rm -rf dist/*

tools/enable-version-filter
rm version
git checkout version
cp version dist
cp version $( rpm --eval %_sourcedir )
tools/disable-version-filter

gitdate=$( date +'%y%m%d' )
head=$( git rev-parse HEAD )
sed -ri -e '/%global commit/s/commit.*/commit '$head/ \
        -e '/%global gitdate/s/gitdate.*/gitdate '$gitdate/ \
        -e '/%changelog/,/^$/ s/git[0-9a-f]{7}/git'"${head:0:7}/" \
        -e '/%changelog/,/^$/ s/[0-9]*git/'"${gitdate}git/" \
     system-config-repo.spec
evr=$( rpm --specfile -q --qf "%{VERSION}-%{RELEASE}" system-config-repo.spec )
read tag tarball < <(spectool -l system-config-repo.spec)
git archive -o $(rpm --eval %_sourcedir)/$(basename $tarball) \
            --prefix system-config-repo-$head/  HEAD

rpmbuild -ba system-config-repo.spec

cp system-config-repo.spec dist
cp $(rpm --eval %_srcrpmdir)/system-config-repo-$evr.src.rpm dist
cp $(rpm --eval %_rpmdir)/noarch/system-config-repo-$evr.noarch.rpm dist
cp  $(rpm --eval %_sourcedir)/$(basename $tarball) dist

git checkout system-config-repo.spec
tools/enable-version-filter
